name: Deploy React App to Ubuntu

on:
  push:
    branches:
      - develope

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.REACT_SSH_PRIVATE_KEY }}

      - name: Sync files to server
        env:
          SERVER_USER: ${{ secrets.SERVER_REACT }}
          SERVER_IP: ${{ secrets.SERVER_REACT_IP }}
          APP_DIR: ${{ secrets.APP_REACT_DIR }}
        run: |
          rsync -avz --exclude=.git ./client/build/ $SERVER_USER@$SERVER_IP:$APP_DIR
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            pm2 reload all
          "
